### ISSUE TITLE
Edit MainCatigory Form - $index is not defined

### ISSUE THREAD

**Issue by nizarghrairi** [ahmedeagle/ecommerce#2]
Hello, 

There is a problem with the resources/views/admin/maincategories/edit.blade.php script.

On line 156, you are using **undeclared** variable `$index`.

I think that you need to start a `foreach` loop before creating the panels.

Regards.

**Comment by senbai** [comment]
hey @nizarghrairi  if you believe this is an issue in the code itself, you can request PR to the owner.
